### ISSUE TITLE
Scan Barcode Method is not Working

### ISSUE THREAD

**Issue by Vladeouz** [Mahmoudmv91/pax_player#1]
my device is A920,

and this is the method to call the scan barcode
` Future<void> _getBarcode() async {
    setState(() {
      _barcodeData = 'please scan barcode data';
    });
    String? number;

    try {
      String? result = await PaxPlayer().getScanBarcode();
      if (result != null) {
        number = 'Success';
      }
    } on PlatformException catch (e) {
      number = 'Error get the barcode: ${e.message}';
    }
    if (!mounted) return;
    setState(() {
      _barcodeData = number!;
    });
    await PaxPlayer().getBeep(100);
  }`

and this is the error that i got.

`Launching lib\main.dart on A920 in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk
Connecting to VM Service at ws://127.0.0.1:55315/vkGLpMKwYhQ=/ws
E/art     ( 1872): No implementation found for int pax.util.OsPaxApi.ScanOpenHW() (tried Java_pax_util_OsPaxApi_ScanOpenHW and Java_pax_util_OsPaxApi_ScanOpenHW__)
W/System.err( 1872): com.pax.api.scanner.hw.ScannerHwException: Not Support for this device
W/System.err( 1872): 	at com.pax.api.scanner.hw.ScannerManagerHw.scanOpen(SourceFile:69)
W/System.err( 1872): 	at com.pax.dal.impl.ScannerHwImpl.open(SourceFile:49)
W/System.err( 1872): 	at pax.plugin.pki.parhamkish.vakili.pax_player.PaxPlayerPlugin.lambda$onMethodCall$3$pax-plugin-pki-parhamkish-vakili-pax_player-PaxPlayerPlugin(PaxPlayerPlugin.java:125)
W/System.err( 1872): 	at pax.plugin.pki.parhamkish.vakili.pax_player.PaxPlayerPlugin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass)
W/System.err( 1872): 	at java.lang.Thread.run(Thread.java:818)
W/System.err( 1872): com.pax.dal.exceptions.ScannerHwDevException: SCANNERHW#100(not support error)
W/System.err( 1872): 	at com.pax.dal.impl.ScannerHwImpl.open(SourceFile:52)
W/System.err( 1872): 	at pax.plugin.pki.parhamkish.vakili.pax_player.PaxPlayerPlugin.lambda$onMethodCall$3$pax-plugin-pki-parhamkish-vakili-pax_player-PaxPlayerPlugin(PaxPlayerPlugin.java:125)
W/System.err( 1872): 	at pax.plugin.pki.parhamkish.vakili.pax_player.PaxPlayerPlugin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass)
W/System.err( 1872): 	at java.lang.Thread.run(Thread.java:818)
I/Timeline( 1872): Timeline: Activity_idle id: android.os.BinderProxy@c71f2ff time:85398751
`

**Comment by Mahmoudmv91** [comment]
Hi @Vladeouz 
Thank you for using my package.
Have you installed all the prerequisites and configured everything correctly? I have tested the project and it works fine. If you are still facing issues, please provide more details so I can assist you better.
